server:
  port: 8083  #tomcat 启动端口号

#服务注册中心配置
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
    healthcheck:
      enabled: true
